#dataset: cifar10
#clsmodel: vgg11
#epochs: 50
#train-epoch: 1
#mode: all2one
#target_label: 0
#epochs_per_external_eval: 10
#cls_test_epochs: 5
#verbose: 2
#batch-size: 128
#alpha: 0.5
#eps: 0.01
#avoid_clsmodel_reinitialization: True
#test_eps: 0.01
#test_alpha: 0.5
#test_epochs: 250
#test_lr: 0.01
#schedulerC_lambda: 0.1
#schedulerC_milestones: 50,100,150,200
#test_use_train_best: True
#seed: 999
#device: cuda:0
#dataset_path: ../data
#random_rotation: 10
#random_crop: 5
#pretensor_transform: False
#num_workers: 2
#batch_size: 64
#lr: 0.01
#lr_atk: 0.0001
#save_model: False
#train_epoch: 1
#attack_model: autoencoder
#best_threshold: 0.1
#test_n_size: 10
#test_optimizer: sgd
#test_use_train_last: False
#use_data_parallel: False

train-epoch: 1
batch-size: 128

device: cuda:0
dataset: cifar10
dataset_path: ../data
random_rotation: 10
random_crop: 5
pretensor_transform: False
num_workers: 2
batch_size: 64
epochs: 50
lr: 0.01
lr_atk: 0.0001
seed: 999
save_model: False
train_epoch: 1
target_label: 0
eps: 0.01
alpha: 0.5
clsmodel: vgg11
attack_model: autoencoder
mode: all2one
epochs_per_external_eval: 10
cls_test_epochs: 5
best_threshold: 0.1
verbose: 2
avoid_clsmodel_reinitialization: True
test_eps: 0.01
test_alpha: 0.5
test_epochs: 250
test_lr: 0.01
schedulerC_lambda: 0.1
schedulerC_milestones: 50,100,150,200
test_n_size: 10
test_optimizer: sgd
test_use_train_best: True
test_use_train_last: False
use_data_parallel: False