attack: refool
attack_label_trans: all2one
attack_target: 0
r_adv_img_folder_path: ../resource/refool/Refool-SelectedReflectionImages/selected_out-images
pratio: 0.0012 # this is clean label and we know default to use 20% of target class, the class0 in gtsrb are 221 photos
num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:0
client_optimizer: sgd
dataset: gtsrb
dataset_path: ../data
frequency_save: 50
batch_size: 32
lr: 0.01
lr_scheduler: MultiStepLR
model: resnet34
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 200
steplr_milestones: # which said to be every 10^5 training steps, about 82 epochs for gtsrb
  - 82
  - 164
  - 246
steplr_gamma: 0.1