device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'cifar100'

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: 'preactresnet18'

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-4
frequency_save: 0

random_seed: 0
unlearning_epochs: 5
lr_unlearning_init: 5.0e-4
momentum: 0.9
weight_decay: 1.0e-4
gradient_ascent_type: 'Flooding'
gamma: 0.5
flooding: 0.5

to_file: True
n_times_test: 1
use_norm: 1
EPSILON: 1.0e-7
mask_lr: 0.1
nc_epoch: 80
init_cost: 1.0e-3
cost_multiplier: 2
atk_succ_threshold: 98.0
early_stop: True
early_stop_threshold: 0.99
early_stop_patience: 25
patience: 5
cost_multiplier: 2